version: "3"

services:
  app:
    build: .
    container_name: django-gunicorn
    restart: always
    env_file:
      - django.env
    volumes:
      - /var/dockerdata/django/src:/src
    ports:
      - "8000:8000"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 mysite.wsgi:application"

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "9999:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
